const myDatabase = [
  {
    id: 1,
    cityName: "Delhi",
    housing: "24.3K",
    food: "15K",
    waterSupply: "3.4K",
    electricitySupply: "24K",
    transportation: "5569",
    internetSupply: "8.4K",
    fuelPrices: "120",
    gasPrices: "800",
    totalCost: 45000,
    gdbPerCapita: "6.2L",
    humanFreedomIndex: 45,
    lifeExpectancy: 61,
  },
  {
    id: 2,
    cityName: "Mumbai",
    housing: "54K",
    food: "17K",
    waterSupply: "10K",
    electricitySupply: "40K",
    transportation: '10K',
    internetSupply: '1200',
    fuelPrices: '130',
    gasPrices: '900',
    totalCost: 72000,
    gdbPerCapita: '2L',
    humanFreedomIndex: 122,
    lifeExpectancy: 57,
  },
  {
    id: 3,
    cityName: "Chennai",
    housing: '33K',
    food: '20K',
    waterSupply: '2.3K',
    electricitySupply: '2.3K',
    transportation: '4K',
    internetSupply: '1.5K',
    fuelPrices: '106',
    gasPrices: '678',
    totalCost: 50000,
    gdbPerCapita: '4.1L',
    humanFreedomIndex: 102,
    lifeExpectancy: 35,
  },
  {
    id: 4,
    cityName: "Kolkata",
    housing: '15K',
    food: '23K',
    waterSupply: '500',
    electricitySupply: '12K',
    transportation: '1.4K',
    internetSupply: '800',
    fuelPrices: '101',
    gasPrices: '700',
    totalCost: 56000,
    gdbPerCapita: '2L',
    humanFreedomIndex: 139,
    lifeExpectancy: 23,
  },
  {
    id: 5,
    cityName: "Hyderabad",
    housing: '45K',
    food: '10.45K',
    waterSupply: '17K',
    electricitySupply: '20K',
    transportation: '1.4K',
    internetSupply: '1.5K',
    fuelPrices: '118',
    gasPrices: '780',
    totalCost: 67000,
    gdbPerCapita: '4L',
    humanFreedomIndex: 56,
    lifeExpectancy: 85,
  },
  {
    id: 6,
    cityName: "Bangalore",
    housing: '35K',
    food: '23K',
    waterSupply: '19K',
    electricitySupply: '4.6K',
    transportation: '4K',
    internetSupply: '900',
    fuelPrices: '115',
    gasPrices: '1.3K',
    totalCost: 65000,
    gdbPerCapita: '5.6L',
    humanFreedomIndex: 108,
    lifeExpectancy: 56,
  },
  {
    id: 7,
    cityName: "Pune",
    housing: '50K',
    food: '1.4K',
    waterSupply: '30K',
    electricitySupply: '40K',
    transportation: '1.9K',
    internetSupply: '1.3K',
    fuelPrices: '121',
    gasPrices: '980',
    totalCost: 42000,
    gdbPerCapita: '1.5L',
    humanFreedomIndex: 117,
    lifeExpectancy: 21,
  },
  {
    id: 8,
    cityName: "Lucknow",
    housing: '45K',
    food: '12K',
    waterSupply: '3.5K',
    electricitySupply: '4K',
    transportation: '7K',
    internetSupply: '768',
    fuelPrices: '115',
    gasPrices: '900',
    totalCost: 27000,
    gdbPerCapita: '1.1L',
    humanFreedomIndex: 111,
    lifeExpectancy: 25,
  },
  {
    id: 9,
    cityName: "Ahmedabad",
    housing: '23K',
    food: '10K',
    waterSupply: '1.4K',
    electricitySupply: '3.4K',
    transportation: '12K',
    internetSupply: '1.2K',
    fuelPrices: '118',
    gasPrices: '1K',
    totalCost: 37000,
    gdbPerCapita: '3.7L',
    humanFreedomIndex: 76,
    lifeExpectancy: 28,
  },
  {
    id: 10,
    cityName: "Jaipur",
    housing: '22K',
    food: '15K',
    waterSupply: '2K',
    electricitySupply: '17K',
    transportation: '5K',
    internetSupply: '800',
    fuelPrices: '102',
    gasPrices: '700',
    totalCost: 29000,
    gdbPerCapita: '2L',
    humanFreedomIndex: 50,
    lifeExpectancy: 78,
  },
];
export default myDatabase;
